### ISSUE TITLE
Useage? How?

### ISSUE THREAD

**Issue by Matix-Media** [ImageGlass/ImageGlass-Photos#2]
Hey, how can I use the prettier version of ImageGlass? :D
I'm an active ImageGlass user and this version seems pretty cool. But how can I use it?

**Comment by d2phap** [comment]
Oh this is just my experiment on electronjs, but there are lots of challenges. Hence, there are no future plan on this.

Thanks for the question :)

**Comment by Matix-Media** [comment]
I like the design of it a lot. Which framework are you currently using? WPF?
